/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package first;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        // System.out.println(new App().getGreeting());
        student st = new student();
        st.setId(100);
        st.setName("test");

        studimpl ob;
        ob = new studimpl();
        ob.update(st);

    }
}
